apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: default
data:
  APPLICATION_NAME: "order-service"
  LIQUIBASE_ENABLED: "true"
  LIQUIBASE_CHANGE_LOG: "classpath:/db/changelog/db.changelog-master.yaml"
  SHOW_SQL: "false"
  FORMAT_SQL: "true"
  LOG_SQL: "DEBUG"
  DB_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  DB_DRIVER: "org.postgresql.Driver"
  KAFKA_CONSUMER_GROUP_ID: "order-service-group"
  KAFKA_KEY_DESERIALIZER: "org.apache.kafka.common.serialization.StringDeserializer"
  KAFKA_VALUE_DESERIALIZER: "org.springframework.kafka.support.serializer.JsonDeserializer"
  SPRING_JSON_TRUSTED_PACKAGES: "*"
  SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING: "true"
  SPRING_AOP_AUTO: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
  RESILIENCE4J_CIRCUITBREAKER_ENABLED: "true"
  FEIGN_CIRCUITBREAKER_ENABLED: "false"